service: nest-serverless-lambda

frameworkVersion: '3'

provider:
 name: aws
 runtime: nodejs18.x
 arquitecture: arm64
 stage: production
 region: us-west-1
 memorySize: 2048
 logRetentionInDays: 1
 timeout: 15

functions:
 api: 
   handler: dist/lambda.handler
   events:
     - http:
         method: any
         path: /{proxy+}


plugins:
 - serverless-jetpack
 - serverless-offline